### ISSUE TITLE
Support machine-friendly output formats

### ISSUE THREAD

**Issue by dumbbell** [rabbitmq/rabbitmq-cli#38] opened 2016-05-24 09:26 UTC
Our CLI tools should be able to output multiple formats for both humans and machines consumption.

The simplest use case is the combination with Unix commands, such as cut(1) or awk(1). Lists and tables should formatted with easy integration with those tools in mind.

A more advanced example is what is done with [libxo](https://github.com/Juniper/libxo): it is used by standard Unix tools to format XML, JSON or HTML, in addition to the expected human-readable output.

Finally, on Windows, PowerShell offers commands the possibility to exchange "objects", skipping parsing entirely if I understand correctly. I have no idea how it works but it seems powerful.

**Comment by michaelklishin** [comment] 2016-11-15 19:06
Further addressed by https://github.com/rabbitmq/rabbitmq-cli/issues/115.

**Comment by michaelklishin** [comment] 2017-01-12 13:14
FWIW the core of multi-format support is there. We are not 100% happy with the state of things at the moment but there's only so much time left in the `3.7.0` cycle. Considering this closed with further improvements we have in mind.

**Closed by michaelklishin** 2017-01-12 13:14 UTC
Labels: effort-medium, enhancement

**Comment by visbits** [comment] 2019-03-08 17:51
So how about this now..

**Comment by michaelklishin** [comment] 2019-03-08 18:06
@visbits if there's a question, consider asking on the mailing list.

Some commands support `--formatter=json`, possibly even `--formatter=csv`. It doesn't make sense for all commands and in some cases the output could be formatted much better. We've concluded that we want to support multiple formatters better but there's a fair amount of command-specific work and we have close to 100 commands now. So the degree of support varies and for some commands, JSON and CSV are not supported by design.

Here are some examples with `3.7.13`:

```
rabbitmqctl list_vhosts --formatter=json | jq
[
  {
    "name": "/"
  }
]

rabbitmqctl list_users --formatter=json | jq
[
  {
    "user": "guest",
    "tags": [
      "administrator"
    ]
  }
]

rabbitmqctl list_parameters --formatter=json | jq
[
  {
    "component": "federation-upstream",
    "name": "up-hare",
    "value": "{\"expires\":3600000,\"uri\":\"amqp://localhost:5673\"}"
  }
]

rabbitmqctl list_queues --formatter=json | jq
[
  {
    "name": "q1",
    "messages": 0
  },
  {
    "name": "amq.gen-IdssHRoMD4umuqnuHCGdaQ",
    "messages": 0
  }
]

rabbitmqctl list_consumers --formatter=json | jq
[
  {
    "queue_name": "amq.gen-IdssHRoMD4umuqnuHCGdaQ",
    "channel_pid": "#PID<10132.853.0>",
    "consumer_tag": "bunny-1552068127000-449053712679",
    "ack_required": false,
    "prefetch_count": 0,
    "arguments": []
  }
]

rabbitmq-diagnostics listeners --formatter=json | jq
{
  "listeners": [
    {
      "interface": "[::]",
      "node": "rabbit@warp10",
      "port": 25672,
      "protocol": "clustering",
      "purpose": "inter-node and CLI tool communication"
    },
    {
      "interface": "[::]",
      "node": "rabbit@warp10",
      "port": 5672,
      "protocol": "amqp",
      "purpose": "AMQP 0-9-1 and AMQP 1.0"
    },
    {
      "interface": "[::]",
      "node": "rabbit@warp10",
      "port": 5671,
      "protocol": "amqp/ssl",
      "purpose": "AMQP 0-9-1 and AMQP 1.0 over TLS"
    },
    {
      "interface": "[::]",
      "node": "rabbit@warp10",
      "port": 15672,
      "protocol": "http",
      "purpose": "HTTP API"
    },
    {
      "interface": "[::]",
      "node": "rabbit@warp10",
      "port": 15671,
      "protocol": "https",
      "purpose": "HTTP API over TLS (HTTPS)"
    },
    {
      "interface": "[::]",
      "node": "rabbit@warp10",
      "port": 1883,
      "protocol": "mqtt",
      "purpose": "MQTT"
    }
  ],
  "result": "ok"
}

rabbitmq-diagnostics alarms --formatter=json | jq
{
  "alarms": [],
  "node": "rabbit@warp10",
  "result": "ok"
}
```
